---
# Ansible playbook for an AWX server.
#
# @author Jeff Geerling (2017).

- hosts: awx-monolith
  gather_facts: yes
  become: yes

  vars_files:
    - vars/main.yml

  roles:
    - name: geerlingguy.repo-epel
      when: ansible_os_family == 'RedHat'
    - geerlingguy.git
    - geerlingguy.ansible
    - geerlingguy.pip
    - geerlingguy.nodejs
    - geerlingguy.postgresql
    - geerlingguy.memcached
    - geerlingguy.rabbitmq
    - geerlingguy.awx
